"""fix users model and roles model added.

Revision ID: 48f3e7a275a3
Revises: 1fee0e520d51
Create Date: 2025-12-18 16:33:55.227334

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48f3e7a275a3"
down_revision = "1fee0e520d51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(length=32), nullable=False))
        batch_op.add_column(
            sa.Column("password", sa.String(length=128), nullable=False)
        )
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=16), nullable=False)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("role_id", sa.Integer(), nullable=False))
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(None, ["username"])
        batch_op.create_unique_constraint(None, ["display_name"])
        batch_op.create_foreign_key(None, "roles", ["role_id"], ["id"])
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.drop_column("role_id")
        batch_op.drop_column("created_at")
        batch_op.drop_column("display_name")
        batch_op.drop_column("password")
        batch_op.drop_column("username")

    op.drop_table("roles")
    # ### end Alembic commands ###
